export const productos = [
  {
    id: 1,
    nombre: "Zapato cafe",
    precio: 500,
    categoria: "Calzado",
    inventario: 23,
    descripcion: "Zapato cafe para hombre",
    img: "",
  },
  {
    id: 2,
    nombre: "Zapato negro",
    precio: 500,
    categoria: "Calzado",
    inventario: 34,
    descripcion: "Zapato negro para hombre",
    img: "",
  },
  {
    id: 3,
    nombre: "Tenis blancos",
    precio: 450,
    categoria: "Calzado",
    inventario: 54,
    descripcion: "Tenis blancos para hombre",
    img: "",
  },
  {
    id: 4,
    nombre: "Tenis negros",
    precio: 450,
    categoria: "Calzado",
    inventario: 34,
    descripcion: "Tenis negros para hombre",
    img: "",
  },
  {
    id: 5,
    nombre: "Sandalias",
    precio: 300,
    categoria: "Calzado",
    inventario: 23,
    descripcion: "Sandalias de playa",
    img: "",
  },
];
